variable "cluster_name" {
  description = "Cluster name prefix for resource naming and tagging."
  type        = string
}

variable "ami_id" {
  description = "AMI ID for the head node. Must be the output of the BurstLab Packer build (centos8-slurm2205). This AMI has Slurm 22.05.11, slurmctld, slurmdbd, and all dependencies pre-installed."
  type        = string
}

variable "instance_type" {
  description = "EC2 instance type for the head node. m7a.large provides 2 vCPU / 8 GB RAM — sufficient for slurmctld + slurmdbd + the aws-plugin-for-slurm on a small lab cluster."
  type        = string
  default     = "m7a.large"
}

variable "key_name" {
  description = "EC2 key pair name for SSH access to the head node. Must already exist in the target AWS account/region."
  type        = string
}

variable "subnet_id" {
  description = "Subnet ID for the head node (management subnet). The head node is placed in the management subnet so it can have a public EIP for SSH access."
  type        = string
}

variable "sg_id" {
  description = "Security group ID for the head node. Should allow SSH (22) from internet and all VPC traffic."
  type        = string
}

variable "instance_profile_arn" {
  description = "ARN of the head node IAM instance profile. Grants the head node permission to call EC2 Fleet APIs and pass the burst node role."
  type        = string
}

variable "onprem_route_table_id" {
  description = "Route table ID for the on-prem compute subnet. After EC2 launch, an aws_route is added here pointing 0.0.0.0/0 → head node ENI (NAT for compute nodes)."
  type        = string
}

variable "cloud_route_table_id" {
  description = "Route table ID for the cloud burst subnets. After EC2 launch, an aws_route is added here pointing 0.0.0.0/0 → head node ENI (NAT for burst nodes)."
  type        = string
}

variable "munge_key_b64" {
  description = "Base64-encoded Munge key (1024 random bytes). Injected into UserData and written to /etc/munge/munge.key on the head node. All cluster nodes must share this exact key — Munge rejects authentication tokens signed with a different key."
  type        = string
  sensitive   = true
}

variable "slurmdbd_db_password" {
  description = "Password for the slurmdbd MariaDB database user. Generated by Terraform random_password. Injected into slurmdbd.conf via UserData."
  type        = string
  sensitive   = true
}

variable "efs_dns_name" {
  description = "EFS filesystem DNS name. Used in the UserData script to mount /home and /opt/slurm via NFS."
  type        = string
}

variable "efs_home_access_point_id" {
  description = "EFS access point ID for the /home export."
  type        = string
}

variable "efs_slurm_access_point_id" {
  description = "EFS access point ID for the /opt/slurm export."
  type        = string
}

variable "compute_node_count" {
  description = "Number of on-prem compute nodes (compute01..N). Used in slurm.conf NodeName definitions."
  type        = number
  default     = 4
}

variable "onprem_cidr" {
  description = "CIDR of the on-prem compute subnet. Used in iptables MASQUERADE rules to NAT traffic from compute nodes."
  type        = string
}

variable "cloud_cidr_a" {
  description = "CIDR of cloud burst subnet A. Used in iptables MASQUERADE rules to NAT traffic from burst nodes."
  type        = string
}

variable "cloud_cidr_b" {
  description = "CIDR of cloud burst subnet B. Used in iptables MASQUERADE rules."
  type        = string
}

variable "slurm_conf" {
  description = "Rendered content of slurm.conf (from templatefile() in locals.tf). Written to /opt/slurm/etc/slurm.conf on EFS so all nodes share the same config."
  type        = string
}

variable "slurmdbd_conf" {
  description = "Rendered content of slurmdbd.conf (from templatefile() in locals.tf). Contains DB connection details with the generated password."
  type        = string
  sensitive   = true
}

variable "cgroup_conf" {
  description = "Content of cgroup.conf. Controls how Slurm enforces resource limits via Linux cgroups on all nodes."
  type        = string
}

variable "plugin_config_json" {
  description = "Rendered content of plugin_config.json for aws-plugin-for-slurm. Contains region, cluster name, launch template ID, and subnet IDs."
  type        = string
}

variable "partitions_json" {
  description = "Rendered content of partitions.json for aws-plugin-for-slurm. Defines burst partition name, node group, instance type, and max nodes."
  type        = string
}

variable "aws_region" {
  description = "AWS region. Written into plugin_config.json and used by the aws-plugin-for-slurm Python scripts."
  type        = string
  default     = "us-west-2"
}

variable "static_private_ip" {
  description = "Static private IP address assigned to the head node. MUST be in the management subnet CIDR (10.0.0.0/24). Default 10.0.0.10 — .1 through .4 are reserved by AWS in every subnet, and .10 leaves room for future gateway-type resources. This static IP is required to break the Terraform circular dependency: slurm.conf and the burst node launch template both reference the head node IP, but both must be created before the head node EC2 instance. Knowing the IP in advance solves this."
  type        = string
  default     = "10.0.0.10"
}
