# =============================================================================
# LOCALS — BurstLab Gen 1
# =============================================================================
# This file handles two concerns:
#   1. Simple computed values (AMI selection, CIDRs)
#   2. templatefile() calls that render Slurm config files
#
# WHY render configs in locals?
#   Slurm config files need values that span multiple modules (head node IP,
#   launch template ID, subnet IDs, etc.). Locals can reference all module
#   outputs in one place, keeping the config rendering logic centralized.
#
# All config templates live under:
#   configs/gen1-slurm2205-rocky8/
# relative to the repo root (two directories up from this file).
# =============================================================================

locals {
  # ---------------------------------------------------------------------------
  # AMI selection
  # ---------------------------------------------------------------------------
  # Use compute_node_ami if explicitly set, otherwise fall back to head_node_ami.
  # In most BurstLab deployments all nodes use the same AMI — this just makes
  # it convenient to override for testing without changing the head node.
  effective_compute_ami = var.compute_node_ami != "" ? var.compute_node_ami : var.head_node_ami

  # ---------------------------------------------------------------------------
  # Head node static private IP
  # ---------------------------------------------------------------------------
  # The head node is assigned a static private IP (10.0.0.10) in the management
  # subnet. This is used in slurm.conf (SlurmctldHost), slurmdbd.conf, and the
  # burst node launch template UserData — all of which must be rendered BEFORE
  # the EC2 instance is created.
  #
  # Using a static IP breaks the Terraform circular dependency:
  #   slurm.conf needs head_node_ip → but slurm.conf is input to head_node → cycle
  # With a statically known IP, there is no dependency on module.head_node at
  # config-rendering time.
  head_node_private_ip = var.head_node_static_ip

  # ---------------------------------------------------------------------------
  # Config template base path
  # ---------------------------------------------------------------------------
  # path.module is this directory (generations/gen1-slurm2205-rocky8/).
  # Configs live two levels up at the repo root under configs/.
  config_dir = "${path.module}/../../../configs/gen1-slurm2205-rocky8"

  # ---------------------------------------------------------------------------
  # slurm.conf
  # ---------------------------------------------------------------------------
  # The main Slurm configuration file. Controls scheduler behavior, node
  # definitions, partition definitions, and cloud bursting plugin settings.
  #
  # The head node's static private IP (local.head_node_private_ip = 10.0.0.10)
  # is used here so slurm.conf can be fully rendered before the EC2 instance is
  # created — avoiding the circular dependency between the head node instance and
  # its own config files.
  #
  # burst_node_conf is left empty here — generate_conf.py generates the burst
  # node NodeName/NodeSet/Partition lines at runtime and appends them.
  slurm_conf = templatefile("${local.config_dir}/slurm.conf.tpl", {
    cluster_name       = var.cluster_name
    head_node_ip       = local.head_node_private_ip
    compute_node_count = var.compute_node_count
    slurm_prefix       = "/opt/slurm"
    burst_node_conf    = "" # Populated at runtime by generate_conf.py
  })

  # ---------------------------------------------------------------------------
  # slurmdbd.conf
  # ---------------------------------------------------------------------------
  # Configuration for the Slurm Database Daemon. Contains:
  #   - DbdHost: the head node's hostname (slurmctld talks to slurmdbd locally)
  #   - StoragePass: the MariaDB password (generated by random_password)
  #   - StorageUser: slurm (standard convention)
  #   - StorageLoc: slurm_acct_db (database name)
  slurmdbd_conf = templatefile("${local.config_dir}/slurmdbd.conf.tpl", {
    # slurmdbd.conf.tpl only uses slurmdbd_db_password. The other values are
    # passed for documentation completeness but the template has them hard-coded
    # (DbdHost=headnode, StorageHost=localhost, etc.) since slurmdbd always runs
    # on the head node alongside MariaDB.
    cluster_name         = var.cluster_name
    slurmdbd_db_password = random_password.slurmdbd_db.result
    slurm_prefix         = "/opt/slurm"
  })

  # ---------------------------------------------------------------------------
  # cgroup.conf
  # ---------------------------------------------------------------------------
  # cgroup.conf doesn't vary by deployment — it's static. We read the file
  # directly rather than using templatefile() to keep things simple.
  # cgroups are used by Slurm to enforce CPU/memory limits per job step.
  cgroup_conf = file("${local.config_dir}/cgroup.conf")

  # ---------------------------------------------------------------------------
  # Helper scripts path
  # ---------------------------------------------------------------------------
  # validate-cluster.sh and demo-burst.sh are uploaded to S3 by main.tf and
  # downloaded by the head node at boot time. Storing scripts in S3 avoids
  # embedding their full text in UserData (which would exceed the 16 KB EC2
  # limit even after gzip compression).
  scripts_dir = "${path.module}/../../../scripts"

  # ---------------------------------------------------------------------------
  # plugin_config.json (aws-plugin-for-slurm)
  # ---------------------------------------------------------------------------
  # Configuration for the aws-plugin-for-slurm Python plugin. Contains:
  #   - Region: us-west-2
  #   - ClusterName: used to tag/identify burst instances
  #   - LaunchTemplateId: the burst node launch template created by burst-config
  #   - SubnetIds: the two cloud burst subnet IDs
  #   - MaxNodes: maximum concurrent burst nodes (safety limit)
  #
  # This file is written to /opt/slurm/etc/plugin_config.json on EFS so
  # aws-plugin-for-slurm can find it at its default config path.
  plugin_config_json = templatefile("${local.config_dir}/plugin_config.json.tpl", {
    aws_region          = var.aws_region
    cluster_name        = var.cluster_name
    launch_template_id  = module.burst_config.launch_template_id
    cloud_subnet_a_id   = module.vpc.cloud_subnet_a_id
    cloud_subnet_b_id   = module.vpc.cloud_subnet_b_id
    max_burst_nodes     = var.max_burst_nodes
    slurm_prefix        = "/opt/slurm"
  })

  # ---------------------------------------------------------------------------
  # partitions.json (aws-plugin-for-slurm)
  # ---------------------------------------------------------------------------
  # Defines the burst partition(s) for aws-plugin-for-slurm. Each entry maps
  # a Slurm PartitionName to an EC2 launch configuration.
  #
  # IMPORTANT naming rules:
  #   PartitionName and NodeGroupName must be ALPHANUMERIC ONLY.
  #   The plugin constructs burst node names as: {PartitionName}-{NodeGroupName}-{N}
  #   Example: "cloud" + "burst" → "cloud-burst-0", "cloud-burst-1", ...
  #   Hyphens in the partition or group name would break this convention.
  partitions_json = templatefile("${local.config_dir}/partitions.json.tpl", {
    # partition_name and node_group_name are hard-coded in the template as
    # "cloud" and "burst" respectively. They are NOT template variables in the
    # .tpl file — the values are baked in for Gen 1. They are documented here
    # for clarity about the node naming convention.
    launch_template_id  = module.burst_config.launch_template_id
    cloud_subnet_a_id   = module.vpc.cloud_subnet_a_id
    cloud_subnet_b_id   = module.vpc.cloud_subnet_b_id
    max_burst_nodes     = var.max_burst_nodes
    burst_instance_type = var.burst_node_instance_type
    aws_region          = var.aws_region
    # cluster_name is used in the Tags block of partitions.json so burst nodes
    # are tagged with the correct cluster name when launched.
    cluster_name        = var.cluster_name
  })
}
